Try to use the ES forwarding view (#250)
The ES search request reaches the right backend view, but an exception
is raised and I haven't figured out what causes this, yet.

TypeError: 'HTTPResponse' object is not callable